- name: Install mariadb package (RHEL)
  tags: redhat,db,mariadb
  dnf: 
    name: mariadb
    state: latest
  when: ansible_distribution == "RedHat"

- name: Install mariadb package (Ubuntu)
  tags: db,mariadb,ubuntu 
  apt: 
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"
