- name: Get tarball
  tags: slurm,install
  get_url:
    url="https://download.schedmd.com/slurm/slurm-20.11.8.tar.bz2"
    dest="/home/{{ deploy_user }}/"

- name: Unarchive source
  tags: slurm,unarchive
  unarchive:
    src="/home/{{ deploy_user }}/slurm-20.11.8.tar.bz2"
    dest=/home/{{ deploy_user }}
    copy=no



- name: Install C compiler
  become: yes
  apt:
    update_cache: yes
    name:
      - gcc
      - build-essential
      - cython
    state: present

- name: Slurm | Build & install
  shell: "./configure --sysconfdir=/usr/local/etc --prefix=/usr/local && make -j 4 && make install"
  args:
    chdir: /home/{{ deploy_user }}/slurm-20.11.8/

- name: Slurm | Copy systemd files
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/"
    owner: hpcsys
    group: hpcsys
    remote_src: yes
  loop: 
    - "/home/{{ deploy_user }}/slurm-20.11.8/etc/slurmd.service"
    - "/home/{{ deploy_user }}/slurm-20.11.8/etc/slurmctld.service"
    - "/home/{{ deploy_user }}/slurm-20.11.8/etc/slurmdbd.service"

#- name: Slurm | Copy all slurm onfig files
#  become: yes
#  copy:
#    src: "{{ item }}"
#    dest: "/usr/local/etc/"
#    owner: slurm
#    group: slurm
#    mode: 0444
#  with_fileglob: "/usr/local/etc/slurm.conf"

- name: Slurm | Check if slurm.conf exists
  tags: configure
  stat:
    path: /usr/local/etc/slurm.conf
  register: sconf_exists
 
- name: Slurm | Deploy slurm.conf IF ABSENT
  copy:
    src: slurm.conf
    dest: /usr/local/etc
    directory_mode: 0755
    mode: 0644
  tags: configure
  when: not sconf_exists.stat.exists

- name: Slurm | Deploy slurm.conf IF ABSENT
  copy:
    src: slurm.conf
    dest: /usr/local/etc
    directory_mode: 0755
    mode: 0644
  tags: reconfigure

- name: Slurm | Check if partition.conf exists
  tags: configure
  stat:
    path: /usr/local/etc/partition.conf
  register: pconf_exists

- name: Slurm | Deploy partition.conf IF ABSENT
  copy:
    src: partition.conf
    dest: /usr/local/etc
    directory_mode: 0755
    mode: 0644
  tags: configure
  when: not pconf_exists.stat.exists

- name: Slurm | Deploy partition.conf IF ABSENT
  copy:
    src: partition.conf
    dest: /usr/local/etc
    directory_mode: 0755
    mode: 0644
  tags: reconfigure

  #- name: generate slurm_config file from template
  #template:
  #  src: "{{ slurm_template_file }}"
  #  dest: /usr/local/etc/slurm.conf
  #  owner: slurm
  #  group: slurm
  #  mode: 0400
  
- name: Slurm | Create spool folder
  file:
    path: "/var/spool/slurm"
    owner: slurm
    group: slurm
    mode: 0700
    state: directory

- name: Slurm | Create log folder
  file:
    path: "/var/log/slurm"
    owner: slurm
    group: slurm
    mode: 0700
    state: directory

