- name: Get tarball
  tags: slurm,install
  get_url:
    url="https://download.schedmd.com/slurm/slurm-20.11.8.tar.bz2"
    dest="/home/{{ deploy_user }}/"

- name: Unarchive source
  tags: slurm,unarchive
  unarchive:
    src="/home/{{ deploy_user }}/slurm-20.11.8.tar.bz2"
    dest=/home/{{ deploy_user }}
    copy=no

- name: Install C compiler
  become: yes
  apt:
    update_cache: yes
    name:
      - gcc
      - build-essential
    state: present

- name: Slurm | check slurmd is installed
  service:
    name: slurmd
    state: started
  register: slurm_installed

- name: Slurm | Build & install
  shell: "./configure --sysconfdir=/usr/local/etc --prefix=/usr/local && make -j 4 && make install"
  args:
    chdir: /home/{{ deploy_user }}/slurm-20.11.8/
  when: slurm_installed is failed

- name: Slurm | Copy systemd files
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/"
    owner: hpcsys
    group: hpcsys
  loop: 
    - "/home/{{ deploy_user }}/slurm-service/slurmd.service"
    - "/home/{{ deploy_user }}/slurm-service/slurmctld.service"
    - "/home/{{ deploy_user }}/slurm-service/slurmdbd.service"

- name: Slurm | Copy slurm config files
  template:
    src: "{{ item }}"
    dest: "/usr/local/etc/{{ item }}"
    owner: slurm
    group: slurm 
    mode: '0644'
  with_items:
    - slurm.conf
  notify:
    - restart_slurmctld
    - restart_slurmd

- name: Slurm | Copy slurm config files
  template:
    src: "{{ item }}"
    dest: "/usr/local/etc/{{ item }}"
    owner: slurm
    group: slurm
    mode: '0644'
  with_items:
    - partition.conf
  notify:
    - restart_slurmctld
    - restart_slurmd

#- name: Slurm | Copy all slurm config files
#  become: yes
#  copy:
#    src: "{{ item }}"
#    dest: "/usr/local/etc/"
#    owner: slurm
#    group: slurm
#    mode: 0644
#  with_fileglob:
#    - "/usr/local/etc/slurm.conf"
#    - "/usr/local/etc/partition.conf"
#  notify:
#    - restart_slurmctld
#    - restart_slurmd

- name: Slurm | Create pid directory
  become: yes
  file:
    path: "/var/run/slurm"
    owner: slurm
    group: slurm
    mode: 0700
    state: directory

- name: Slurm | Create pid file
  become: yes
  file:
    path: "/var/run/slurm/slurmd.pid"
    owner: slurm
    group: slurm
    mode: 0644
    state: touch

- name: Slurm | Create spool folder
  file:
    path: "/var/spool/slurm"
    owner: slurm
    group: slurm
    mode: 0700
    state: directory

- name: Slurm | Create log folder
  file:
    path: "/var/log/slurm"
    owner: slurm
    group: slurm
    mode: 0700
    state: directory
