- name: Get tarball
  tags: slurm,install
  get_url:
    url="https://download.schedmd.com/slurm/slurm-20.11.8.tar.bz2"
    dest="/home/{{ deploy_user }}/"

- name: Unarchive source
  tags: slurm,unarchive
  unarchive:
    src="/home/{{ deploy_user }}/slurm-20.11.8.tar.bz2"
    dest=/home/{{ deploy_user }}
    copy=no

- name: Install C compiler
  become: yes
  apt:
    update_cache: yes
    name: 
      - gcc
      - build-essential
    state: present

- name: Configure the tarball
  become: yes
  command: chdir=/home/{{ deploy_user }}/slurm-20.11.8/ ./configure

- name: Make the tarball
  become: yes
  command: chdir=/home/{{ deploy_user }}/slurm-20.11.8/ make

- name: Install the tarball
  become: yes
  command: chdir=/home/{{ deploy_user }}/slurm-20.11.8/ sudo make install

    #- name: Build slurm 
    #shell: "{{ item }}"
    #args:
    #chdir: "/home/{{ deploy_user }}/slurm-20.11.8/"
    #with_items:
    #- ./configure 
    #- make
    #- make install

  #- name: generate slurm_config file from template
  #tags: slurm
  #template: 
  #src: "{{ slurm_template_file }}"
  #dest: /usr/local/etc
  #owner: slurm
  #group: slurm
  #mode: 0644
