- name: Install slurm package (Ubuntu)
  tags: slurm,ubuntu,install
  apt:
    name: slurm-wlm
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: generate slurm_config file from template
  tags: slurm
  template: 
    src: "{{ slurm_template_file }}"
    dest: /etc/slurm-llnl/slurm.conf
    owner: root
    group: root
    mode: 0644
  notify: restart_slurm