- name: add ssh key for hpcsys
  authorized_key: 
    user: hpcsys
    key: "{{ lookup('file', '/home/hpcsys/.ssh/id_rsa.pub') }}"

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd

