- name: add ssh key for hpc
  authorized_key: 
    user: hpc
    key: "{{ lookup('file', '/home/kristiyanslave/.ssh/id_rsa.pub) }}"

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd

