- name: add ssh key for hpc
  authorized_key: 
    user: hpc
    key: "{{ lookup('file', '/home/kristiyanslave/.ssh/id_rsa.pub') }}"

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd

- name: generate slurm_config file from template
  tags: slurm
  template: 
    src: "{{ slurm_template_file }}"
    dest: /etc/slurm-llnl/slurm.conf
    owner: root
    group: root
    mode: 0644
  notify: restart_slurm