                  #Ubuntu
- name: Install apache2 and php packages for Ubuntu
  tags: apache,apache2,ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"
  #when: ansible_distribution in ["Debian", "Ubuntu"]

                    #CentOS 
- name: Install apache and php packages for CentOS
  tags: apache,centos,httpd
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "CentOS"
  #when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Start httpd (CentOS) 
  #starts services on CentOS systems that are not automatically started when installed
  tags: apache,centos,httpd
  service: 
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"


- name: change e-mail address for admin
  tags: apache,centos,httpd
  lineinfile: 
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.net
  when: ansible_distribution == "CentOS"
  register: httpd 

- name: restart httpd (CentOS) 
  tags: apache,centos,httpd
  service: 
    name: httpd
    state: restarted
  when: httpd.changed

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: /home/kristiyanslave/playbooks/linuxmachine/roles/webservers/files/default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
