apache_package_name: httpd
apache_service: httpd
php_package_name: php
ssh_users: "kristiyanslave hpc"
ssh_template_file: sshd_config_centos.j2
slurm_template_file: slurm_config_ubuntu.j2
user_password: "hpc"
user_name: hpc